[package]
name = "stakcast"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.2"
openzeppelin = "1.0.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", branch = "main" }

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true

[dev-dependencies]
snforge_std = "0.44.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true

[cairo]
sierra-replace-ids = true

[scripts]
test = "snforge test"

[lib]
path = "src/lib.cairo"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.snforge]
contracts-path = "target/dev"
